se/urls.py
#-*- coding=utf-8 -*-
from django.conf.urls import patterns, include, url
from secondhand.BasicViews import *
from secondhand.UserViews import *
from secondhand.ProductViews import *
from secondhand.Test import *
from django.contrib import admin
admin.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'se.views.home', name='home'),
    # url(r'^se/', include('se.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    (r'^admin/',include(admin.site.urls)),
)

urlpatterns += patterns('secondhand.ProductViews',
	(r'^$|^index/$', index),
	(r'^product/(\d+)/$', LoginRequired(ProductInfo)),
	(r'^product/add/$', LoginRequired(AddProduct)),
	(r'^search/$', Search),
)
urlpatterns += patterns('secondhand.UserView',
	(r'^login/$', Login),
	(r'^logout/$', LoginRequired(Logout)),
	(r'^editpro/$', LoginRequired(EditPro)),
	(r'^register/$', Register),
	(r'^profile/(\d+)/$', LoginRequired(ShowUser)),
)
urlpatterns += patterns('secondhand.BasicViews',
	(r'^getpic/$', GetPic),
	(r'^getcomments/$', LoginRequired(GetComments)),
)

urlpatterns += patterns('secondhand.Test',
		(r'^test/$', Test),
)
#urlpatterns += patterns('',
		#(r'^(?P<path>.*)$','django.views.static.serve',
		# {
		# 	'document_root':'/home/se/se/secondhand/templates'}
		#),
#)

secondhand/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	name	= models.CharField(max_length=30)
	nick	= models.CharField(max_length=10)
	address	= models.CharField(max_length=100)
	pwd		= models.CharField(max_length=50)
	visits	= models.IntegerField(default=0)
	valid	= models.BooleanField(default=True)	
	def __unicode__(self):
		return '%s %s' %(self.nick,self.name)
	
	def FNNP(self):
		for i in self.phonenumber_set.all():
			if i.num:
				return i
		return None

	def FNNM(self):
		for i in self.mail_set.all():
			if i.address:
				return i
		return None

	class Admin:
		pass
#		list_display=('id','name','nick','valid')
#		ordering=('-id',)
#		search_fields=('id','name','nick',)


class PhoneNumber(models.Model):
	user	= models.ForeignKey(User)
	num		= models.CharField(max_length=12)
	def __unicode__(self):
		return self.num

	class Admin:
		pass
#		list_display=('user','num')
#		ordering=('user',)
#		search_fields=('user','num',)

class Mail(models.Model):
	user	= models.ForeignKey(User)
	address	= models.CharField(max_length=50)
	
	def __unicode__(self):
		return self.address
	class Admin:
		pass
#		list_display=('user','address')
#		ordering=('user',)
#		search_fields=('user','address',)

class Product(models.Model):
	addtime		= models.DateTimeField()
	closetime	= models.DateTimeField(null=True)
	title		= models.CharField(max_length=50)
	descrip		= models.CharField(max_length=1000)
	visits		= models.IntegerField(default=0)
	user		= models.ForeignKey(User)
	valid		= models.BooleanField(default=True)	
	def __unicode__(self):
		return self.title
	class Admin:
		pass
#		list_display=('user','title','valid')
#		ordering=('user',)
#		search_fields=('user','title',)

class CommentUser(models.Model):
	commenttime		= models.DateTimeField()
	commenter_uid	= models.IntegerField(null=False)
	targetuser		= models.ForeignKey(User)
	content			= models.CharField(max_length=1000)
	def getCommenter(self):
		try:
			user = User.objects.get(id = self.commenter_uid)
		except User.DoesNotExist:
			return None
		return user
	class Meta:
		ordering = ['-commenttime']
	class Admin:
		pass

class CommentProduct(models.Model):
	commenttime		= models.DateTimeField()
	commenter_uid	= models.IntegerField(null=False)
	targetproduct	= models.ForeignKey(Product)
	content			= models.CharField(max_length=1000)
	def getCommenter(self):
		try:
			user = User.objects.get(id = self.commenter_uid)
		except User.DoesNotExist:
			return None
		return user
	class Meta:
		ordering = ['-commenttime']
	class Admin:
		pass

secondhand/views.py
# Create your views here.

secondhand/templates/addproduct.html
{% extends "base.html" %}
{% block content %}
<div class="well sidebar">
<form id="addproduct" enctype="multipart/form-data" name="addproduct" action="" method="POST">
	{% csrf_token %}
	<table align="center">
		<tr>
			<td class="span1">
				<label for="title">
				<p>标题</p>
				</label>
			</td>
			<td>
				<input id="title" type="text" size="20" maxlength="16" name="title">
			</td>
		</tr>
		<tr>
			<td class="span1">
				<label for="image">
				<p>图片</p>
				</label>
			</td>
			<td>
				<input id="image" type="file" name="image">
			</td>
		</tr>
		<tr>
			<td class="span1">
				<label for="descrip">
				<p>描述</p>
				</label>
			</td>
			<td>
				<textarea id="descrip" style="resize:none;" maxlength="2048" rows="13" cols="27" name="descrip" value="" class="text ui-widget-content ui-corner-all" placeholder="请写下您的描述"></textarea>
			</td>
		</tr>
		<tr>
			<th align="center" colspan="2">
				<input class="btn" id="submit" type="submit" value="添加">
			</th>
		</tr>
	</table>
</form>
</div>
{% endblock %}

secondhand/templates/base.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>
		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<!-- Le styles -->
		<link href="/static/css/bootstrap.css" rel="stylesheet">
		<style>
			body { padding-top: 60px; /* 60px to make the container go all the way
				to the bottom of the topbar */ }
		</style>
		<link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
		</script>
		<![endif]-->
		<!-- Le fav and touch icons -->
		<link rel="shortcut icon" href="/static/ico/favicon.ico">
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
		<link type="text/css" href="/static/css/custom-theme/jquery-ui.custom.css" rel="stylesheet">
		<link type="text/css" href="/static/css/packed_library.css" rel="stylesheet">
		<link type="text/css" href="/static/css/packed__all.css" rel="stylesheet">
		<link type="text/css" href="/static/css/packed_dialog.css" rel="stylesheet">
		<script type="text/javascript" src="/static/js/jquery.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery-ui.custom.min.js"></script>
		<script type="text/javascript" src="/static/js/base.js"></script>
		<script type="text/javascript" src="/static/js/jquery.ias.min.js"></script>
		<style>
		</style>
		{% block morehead %}{% endblock %}
	</head>

	<body>
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="#">
						GG
					</a>
					<ul class="nav">
						<li>
						<a href="/">
							Home
						</a>
						</li>
						<li>
						<a href="/search/">
							See All>>
						</a>
						</li>
					</ul>
					{% if not isLogin and not reg_or_login %}
					<div class="nav pull-right">
						<li >
						<a href="/register/">
							Register
						</a>
						</li>
					</div>
					<form class="navbar-form pull-right" id="login" name="login" action="/login/" method="post">
						{% csrf_token %}
						<input id="username" name="username" type="text" placeholder="Username" class="span2">
						<input id="password" name="password" type="password" placeholder="Password" class="span2">
						<button class="btn">
							Sign in
						</button>
					</form>
					{% else %}
					<div class="nav pull-right">
						<li>
						<a href='/logout/'>
							logout
						</a>
						</li>
					</div>
					<div class="nav pull-right">
						<li>
						<a href='/profile/{{ loginuser.id }}/'>
							{{ loginuser.nick }}
						</a>
						</li>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<br clear="both" />
		<br clear="both" />
		<br clear="both" />
		{% block content %}
		{% endblock %}
	</body>
	<footer align="center">
	<p></p>
	<p>Copyright © 2012 All Rights Reserved?</p>
	</footer>
	<div id="totop">
		<a href="#"><span><em>返回<br/>顶部</em></span></a>
	</div>
	{% block extend %}{% endblock %}
</html>

secondhand/templates/dialogform/basic.html
<div id="whole">
	{% block result_info %}{% endblock %}
	<form>
		{% csrf_token %}
		<fieldset>
			<div id="label_input">
				{% block formbody %}{% endblock %}
			</div>
		</fieldset>
	</form>
</div>

secondhand/templates/dialogform/comment_form.html
{% extends "dialogform/basic.html" %}
{% block result_info %}
	<!-- <h1>添加评论</h1> -->
	<!-- {{ loginuser.ecncuid }} -->
	<p style="color: red;">
	{% if errors %}
		{% for error in errors %}
			{{ error }}
		{% endfor %}
		 <input id="flag" value="0" style="display:none"></input>
	{% else %}
		 评论成功! 
		 <input id="flag" value="1" style="display:none"></input>
	{% endif %}
	</p>
{% endblock %}
{% block formbody %}
<div >
	<div class="comment_form">
		<!-- <label for="id_comment"></label> -->
		<textarea style="width:10;height:10;" id="id_comment" maxlength="2048" name="comment" value="" class="text ui-widget-content ui-corner-all" placeholder="请写下您的评论"></textarea>
	</div>
</div>
{% endblock%}

secondhand/templates/editpro.html
{% extends "base.html" %}
{% block title%} Register {% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/jquery.js"></script>
<script type="text/javascript">
	function addphone(){
		var formHtml = '<Input type="text" name="phone" maxlength="32" value=""/>'
		$("#addphoneblock").append(formHtml)
	}
	function addmail(){
		var formHtml = '<Input type="text" name="mail" maxlength="32" value=""/>'
		$("#addmailblock").append(formHtml)
	}
	function addClickHandlers(){
		$("#addphone").click(function() {addphone()})
		$("#addmail").click(function() {addmail()})
	}
	$(document).ready(addClickHandlers);
</script>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4">
			<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<div class="">
						<li class="nav-header">
						<img src="/static/img/noavatar_big.gif" alt="{{ loginuser.name }}" />
						</li>
						<li class="nav-header">
					</div>
					<h3>
						{{ loginuser.name }}({{ loginuser.nick }})
					</h3>
					</li>
					<li>
					</li>
					<div class="row-fluid">
						<div class="row-fluid">
							{% if loginuser.FNNP %}
							<label for="id_FNNP" class="span3">Phone:</label>
							<label id="id_FNNP" class="span3">{{ loginuser.FNNP }}</label>
							{% endif %}
						</div>
						<div class="row-fluid">
							{% if loginuser.FNNM %}
							<label for="id_FNNM" class="span3">Email:</label>
							<label id="id_FNNM" class="span3">{{ loginuser.FNNM }}</label>
							{% endif %}
						</div>
						<div class="row-fluid">
							{% if loginuser.address %}
							<label for="id_Uaddress" class="span3">Address:</label>
							<label id="id_Uaddress" class="span3">{{ loginuser.address }}</label>
							{% endif %}
						</div>
					</div>
				</ul>
			</div>
		</div>
		<div class="span8">
			<div class="hero-unit">
				<div>
					<p>
					<h2>
						修改个人信息
					</h2>
					</p>
					<p></p>
					<p>
					<form class="row-fluid" action="" method="POST">
						{% csrf_token %}
						<div class="row-fluid">
							<div class="span2">
								<label for="id_nick">NickName:</label>
							</div>
							<div id="id_nick" class="span2">
								<input type="text" name="nick" maxlength="32" value="{{ loginuser.nick }}"/>
							</div>
						</div>
						<p></p>
						<div class="row-fluid">
							<div class="span2">
								<label for="id_address">Address:</label>
							</div>
							<div id="id_address" class="span2">
								<input type="text" name="address" maxlength="32" value="{{ loginuser.address }}"/>
							</div>
						</div>
						<p></p>
						<div class="row-fluid">
							<div class="span2">
								<label for="id_phone">PhoneNum:</label>
							</div>
							<div id="id_phone" class="span2">
								{% for phone in loginuser.phonenumber_set.all %}
								{% if phone.num %}
								<input type="text" name="phone" maxlength="32" value="{{ phone.num }}"/>
								{% endif %}
								{% endfor %}
								<div id=addphoneblock>
								</div>
								<a class="btn" id="addphone" name="addphone" value="addphone" type="button">AddPhone</a>
							</div>
						</div>
						<p></p>
						<div class="row-fluid">
							<div class="span2">
								<label for="id_mail">Email:</label>
							</div>
							<div id="id_mail" class="span2">
								{% for mail in loginuser.mail_set.all %}
								{% if mail.address %}
								<input type="text" name="mail" maxlength="32" value="{{ mail.address }}"/>
								{% endif %}
								{% endfor %}
								<div id=addmailblock>
								</div>
								<a class="btn" id="addmail" name="addmail" value="addmail" type="button">AddMail</a>
							</div>
						</div>
						<p></p>
						<input type="hidden" name="uid" value="{{ loginuser.id }}"/>
						<input class="btn btn-primary" type="submit" name="submit" value="Save"/>
					</form>
					</p>
				</div>
			</div>
			<div class="row-fluid">
			</div>
			<hr>
		</div>
	</div>
</div>
{% endblock %}

secondhand/templates/productinfo.html
{% extends "base.html" %}
{% block morehead %}
<link type="text/css" href="/static/css/bookInfo.css" rel="stylesheet"/>
<link type="text/css" href="/static/css/form.css" rel="stylesheet"/>
<script type="text/javascript" src="/static/js/csrf.js"></script>
<script>
	var user_id;
	var product_id;
	var page = 1;
	var head = {{ page.head }}
	var tail = {{ page.tail }}
	var opt
	function getcomments() {
		var url = '/getcomments/';
		var tpid = $("#comment").attr('name');
		var cuid = $("#commenter").attr('name');
		if (opt == 'prev')
			page -= 1;
		if (page < head)
			page = head;
		if (opt == "next")
			page += 1;
		if (page > tail)
			page = tail
		$.post(url, {'page':page, 'cuid':cuid, 'tpid':tpid, 'flag':'product'}, function(data) {
				$("#commentlist").html(data);
				});
	}
	function getform(name, method) {
		var url = '/product/' + product_id + '/'
		if (method == "get") {
			$.get(url, {'form_name':name, 'uid':product_id}, function(data) {
				if (name == 'comment') {
					$("#commentproductform").html(data);
					$("#commentproductform").dialog("open");
				}
			});
		}
		else if (method == "post") {
			var content = $("#id_comment").val();
			$.post(url, {'form_name':name, 'comment':content}, function(data) {
				if (name == "comment") {
					$("#commentproductform").html(data);
					$("#commentproductform").dialog("open");
					refreshPage(location.href);
				}
			});
		}
	}
	var refreshPage = function(url) {
		var flag = $("#flag").val();
		if (flag == 1) {
			setTimeout("window.location.assign('" + url + "')", 500);
		}
	}
	function handler() {
		getcomments()
		$("#prevpage").click(function() {opt=$(this).attr('name'); getcomments()});
		$("#nextpage").click(function() {opt=$(this).attr('name'); getcomments()});
		$("#comment").click(function() {product_id=$(this).attr('name'); getform('comment', 'get')});
		$("#commentproductform").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"评论":function() {
					getform('comment', 'post')
				},
				"取消":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#commenproductform").empty()
			}
		});
	}
	$(document).ready(handler);
</script>
{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span5">
			<div class="well sidebar-nav">
				<div class="nav nav-list">
					<div class="row-fluid">
						<div class="row-fluid">
							<label for="id_title" class="span3">标题:</label>
							<label id="id_title" class="span9">{{ product.title }}</label>
						</div>
						<div class="row-fluid">
							<label for="id_publisher" class="span3">发布者:</label>
							<label id="id_publisher" class="span9"><a href="/profile/{{ product.user.id }}">{{ product.user.nick }}</a></label>
						</div>
						<div class="row-fluid">
							<label for="id_status" class="span3">状态:</label>
							<label id="id_status" class="span9">{% if product.valid %}正常{% else %}关闭{% endif %}</label>
						</div>
						<div class="row-fluid">
							<label for="id_addtime" class="span3">添加时间:</label>
							<label id="id_addtime" class="span9">{{ product.addtime|date:"Y-m-d H:i:s" }}</label>
						</div>
						{% if not product.valid %}
						<div class="row-fluid">
							<label for="id_closetime" class="span3">关闭时间:</label>
							<label id="id_closetime" class="span9">{{ product.closetime|date:"Y-m-d H:i:s" }}</label>
						</div>
						{% endif %}
						<div class="row-fluid">
							<label for="id_image" class="span3">图片:</label>
							<a href="/getpic/?uid={{ product.user.id }}&pid={{ product.id }}&size=big">查看大图</a>
							<img src="/getpic/?uid={{ product.user.id }}&pid={{ product.id }}"/>
						</div>
						<div class="row-fluid">
							<label for="id_descrip" class="span3">商品描述:</label>
							<p id="id_descrip" class="span9" >{{ product.descrip }}</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="span7">
			{% if product.user == loginuser %}
			<div class="well sidebar">
				<h3>修改商品信息</h3>
				<form enctype="multipart/form-data" id="modifyproduct" name="modifyproduct" action="" method="POST">
					{% csrf_token %}
					<table align="center">
						<tr>
							<td class="span3">
								<label for="title">
									<p>是否有效</p>
								</label>
							</td>
							<td>
								<input id="valid" type="checkbox" name="checkbox" {% if product.valid %}checked{% endif %} value="True">
							</td>
						</tr>
						<tr>
							<td class="span3">
								<label for="title">
									<p>标题</p>
								</label>
							</td>
							<td>
								<input id="title" type="text" size="20" maxlength="16" name="title" placeholder="请写下商品标题" value="{{ product.title }}" />
							</td>
						</tr>
						<tr>
							<td class="span3">
								<label for="image">
									<p>图片</p>
								</label>
							</td>
							<td>
								<input class="" id="image" type="file" size="20" maxlength="16" name="image" placeholder="请上传图片" />
							</td>
						</tr>
						<tr>
							<td class="span3">
								<label for="descrip">
									<p>描述</p>
								</label>
							</td>
							<td>
								<textarea style="resize:none" id="descrip" maxlength="2048" rows="13" cols="27" name="descrip" value="" class="text ui-widget-content ui-corner-all" placeholder="请写下商品描述">{{ product.descrip }}</textarea>
							</td>
						</tr>
						<tr>
							<th align="center" colspan="2">
								<input class="btn" id="submit" type="submit" value="修改">
							</th>
						</tr>
					</table>
				</form>
			</div>
			{% endif %}
			<div class="hero-unit">
				<h3>评论</h3>
				<div id="commentlist">
				<div class="rr">
					<p>第{{ page.curr }}页  共{{ product.commentproduct_set.all|length }}条记录  {{ page.tail }}页</p>
				</div>
					{% for comment in product.commentproduct_set.all %}
					<div class="row-fluid">
						<fieldset class="well sidebar">
							<legend><a href="/profile/{{ commenter_uid }}">{{ comment.getCommenter.nick }}</a>发表于{{ comment.commenttime|date:"Y-m-d H:i:s" }}</legend>
							<p>
					<pre>{{ comment.content }}</pre>
							<p></p>
							</p>
						</fieldset>
					</div>
					{% endfor %}
					<div id="currpage" name="{{ page.curr }}"></div>
				</div>
				<div id="commenter" name="{{ loginuser.id }}"></div>
				<br clear="both" />
				<div class="paginator" id="pages_navigation">
					<span class="prev">
						<a id="prevpage" name="prev">&lt前页</a>
					</span>
					<span class="next">
						<a id="nextpage" name="next">后页&gt</a>
					</span>
				</div>
				<a id="comment" class="btn btn-primary" name="{{ product.id }}" type="button">
					我也说两句 »
				</a>
			</div>
			<div>
				<div id="dialog_form"></div>
				<div id="commentproductform" title="评论"></div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

secondhand/templates/user.html
{% extends "base.html" %}
{% block morehead %}
<link type="text/css" href="/static/css/bookInfo.css" rel="stylesheet"/>
<link type="text/css" href="/static/css/form.css" rel="stylesheet"/>
<script type="text/javascript" src="/static/js/csrf.js"></script>
<script type="text/javascript" src="/static/js/sechand_dialog.js"></script>
<script type="text/javascript" src="/static/js/hidetext.js"></script>
<script type="text/javascript">
	var page = 1;
	var head = {{ page.head }}
	var tail = {{ page.tail }}
	var opt
	function getcomments() {
		var url = '/getcomments/';
		var tuid = $("#comment").attr('name');
		var cuid = $("#commenter").attr('name');
		if (opt == 'prev')
			page -= 1;
		if (page < head)
			page = head;
		if (opt == "next")
			page += 1;
		if (page > tail)
			page = tail
		$.post(url, {'page':page, 'cuid':cuid, 'tuid':tuid, 'flag':'user'}, function(data) {
				$("#commentlist").html(data);
				});
	}
	function handler() {
		getcomments()
		$("#prevpage").click(function() {opt=$(this).attr('name'); getcomments()});
		$("#nextpage").click(function() {opt=$(this).attr('name'); getcomments()});
	}
	$(document).ready(handler);
</script>
{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4">
			<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<div class="">
						<li class="nav-header">
						<img src="/static/img/noavatar_big.gif" alt="{{ tuser.name }}" />
						</li>
						<li class="nav-header">
					</div>
					<h3>
						{{ tuser.name }}({{ tuser.nick }})
					</h3>
					</li>
					<li>
					</li>
					<div class="row-fluid">
						<div class="row-fluid">
							{% if tuser.FNNP %}
							<label for="id_FNNP" class="span3">Phone:</label>
							<label id="id_FNNP" class="span3">{{ tuser.FNNP }}</label>
							{% endif %}
						</div>
						<div class="row-fluid">
							{% if tuser.FNNM %}
							<label for="id_FNNM" class="span3">Email:</label>
							<label id="id_FNNM" class="span3">{{ tuser.FNNM }}</label>
							{% endif %}
						</div>
						<div class="row-fluid">
							{% if tuser.address %}
							<label for="id_Uaddress" class="span3">Address:</label>
							<label id="id_Uaddress" class="span3">{{ tuser.address }}</label>
							{% endif %}
						</div>
						<div class="row-fluid">
							{% if loginuser == tuser %}
							<form action="/editpro/" method="POST">
								{% csrf_token %}
								<input type="hidden" name=uid value="{{ loginuser.id }}"/>
								<input class="btn" type="submit" name="submit" value="修改个人信息" />
							</form>
							{% endif %}
						</div>
					</div>
				</ul>
			</div>
			{% if loginuser == tuser %}
			<div class="well sidebar">
				<ul class="nav nav-list">
					<li><a href="/product/add/" class="btn" />添加商品</a></li>
				</ul>
			</div>
			{% endif %}
		</div>
		<div class="span8">
			<div class="well sidebar">
				<h3>最新商品</h3>
				<div class="row-fluid">
					{% for product in products1 %}
					<div class="span4">
						<div class="well sidebar-nav">
							<a href="/product/{{ product.id }}/"><h3 name="Title">{% if not product.valid %}(已关闭){% endif %}{{ product.title }}</h3></a>
							<img src="/getpic/?uid={{ product.user.id }}&pid={{ product.id }}">
							<p name="Description">
							{{ product.descrip }}
							</p>
							<a class="btn" href="/product/{{ product.id }}/">
								View details »
							</a>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="row-fluid">
					{% for product in products2 %}
					<div class="span4">
						<div class="well sidebar-nav">
							<a href="/product/{{ product.id }}/"><h3 name="Title">{% if not product.valid %}(已关闭){% endif %}{{ product.title }}</h3></a>
							<img src="/getpic/?uid={{ product.user.id }}&pid={{ product.id }}">
							<p name="Description">
							{{ product.descrip }}
							</p>
							<a class="btn" href="/product/{{ product.id }}/">
								View details »
							</a>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="row-fluid">
					<form class="navbar-form pull-right" id="sraech" name="search" action="/search/" method="get">
						<input type="hidden" name="fromprofile" value="True"/>
						<input type="hidden" name="query" value=""/>
						<input type="hidden" name="user_name" value="{{ tuser.name }}"/>
						<input class="btn" type="submit" name="submit" value="See All>>"/>
					</form> 
				</div>
			</div>
			<div class="hero-unit">
				<h3>个人信用</h3>
				<div id="commentlist">
					<p>第{{ page.curr }}页  共{{ product.commentuser_set.all|length }}条记录  {{ page.tail }}页</p>
					{% for comment in tuser.commentuser_set.all %}
					<div class="row-fluid">
						<fieldset class="well sidebar">
							<legend><a href="/profile/{{ comment.commenter_uid }}">{{ comment.getCommenter.nick }}</a>发表于{{ comment.commenttime|date:"Y-m-d H:i:s" }}</legend>
							<p>
					<pre>{{ comment.content }}</pre>
							<p></p>
							</p>
						</fieldset>
					</div>
					{% endfor %}
					<div id="currpage" name="{{ page.curr }}"></div>
				</div>
				<div id="commenter" name="{{ loginuser.id }}"></div>
				<br clear="both" />
				<div class="paginator" id="pages_navigation">
					<span class="prev">
						<a id="prevpage" name="prev">&lt前页</a>
					</span>
					<span class="next">
						<a id="nextpage" name="next">后页&gt</a>
					</span>
				</div>
				<a id="comment" class="btn btn-primary" name="{{ tuser.id }}" type="button">
					我也说两句 »
				</a>
			</div>
			<div>
				<div id="dialog_form"></div>
				<div id="commentuserform" title="评论"></div>
			</div>
			<hr>
		</div>
	</div>
</div>
{% endblock %}